import { Inter } from "next/font/google";

import { Sidebar } from "@/components/Sidebar";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "CSC",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex min-h-screen">
					<div>
						<Sidebar />
					</div>
					<div className="flex-1">{children}</div>
				</div>
			</body>
		</html>
	);
}
